[package]
name = "http_request"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.17.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.48.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
